### ISSUE TITLE
index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by sassman** [arkaitzj/benchrs#4]
Hey there, great tool!

unfortunately I do encounter a little error:

```sh
$ benchrs -v "http://localhost:8080/"
18:00:15.289 [INFO] benchrs:0.1.7
18:00:15.289 [INFO] Spawning 8 threads
18:00:15.326 [DEBUG] (9) benchrs::fetcher: Fetcher 0 started
18:00:15.337 [DEBUG] (9) benchrs: Producer starting..
18:00:15.337 [DEBUG] (9) benchrs: Producer finalised
18:00:15.339 [ERROR] 1 fetchers failed and 0 succeeded:
Err(Connecting

Caused by:
    Connection refused (os error 61))
...
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/sassmann/.cargo/registry/src/github.com-1ecc6299db9ec823/benchrs-0.1.7/src/main.rs:176:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', /Users/sassmann/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.18/src/task.rs:272:55
```

> Note: I tried also to install with `cargo install benchrs --locked` but ran into the same issue.

```sh
$ benchrs --version
Benchrs 0.1.7
```

smol is meanwhile at version `1.2.5` and is probably very worth to upgrade.

BTW: A little recommendation from rustacean to the other: I use [dependabot](https://dependabot.com/) to keep my dependencies updated on my crates, and that has made my life so much more easier.

**Comment by arkaitzj** [comment]
Good catch, just fixed it, and checking out dependabot...
